name: Test
'on':
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Run tests
        run: yarn run ci:test
        shell: bash
